# Generated by Django 5.2.1 on 2025-06-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avatar',
            field=models.ImageField(default=True, upload_to='book/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.CharField(default=True, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
