# Generated by Django 5.2.1 on 2025-06-10 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author_alter_book_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='book',
        ),
        migrations.AddField(
            model_name='reservation',
            name='book_copy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='books.bookcopy'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('user', 'book_copy'), name='unique_reservation'),
        ),
    ]
