# Generated by Django 5.1.7 on 2025-06-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_reservation_unique_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransaction',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, default='2025-06-18'),
            preserve_default=False,
        ),
    ]
