# Generated by Django 5.2.1 on 2025-05-25 03:27

import accounts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models.TokenBaseClass.get_default_token_expiration),
        ),
        migrations.AlterField(
            model_name='accountverificationtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
